Corrected mistakes
opendevstack/opendevstack.github.io pull request #31
Opened 2018-10-01 11:48 UTC by rattermeyer

Just noticed some left-overs from another site on main page.

2018-10-01 13:28 UTC, tjaeschke requested changes

2018-10-01 13:28 UTC, tjaeschke commented on index.html
> +                        <li>October: Realease V1.0 </li>
Just a small typo Release instead of Realease

2018-10-03 14:29 UTC, clemensutschig submitted a review, later dismissed

2018-10-10 07:38 UTC, tjaeschke approved these changes

2018-10-10 07:46 UTC, merged