Write development guide
opendevstack/opendevstack.github.io pull request #59
Opened 2018-11-23 12:53 UTC by michaelsauter

This is supposed to replace most parts of https://github.com/opendevstack/PMC/blob/b16d605d26a276fec8c216c1e4fb14501dc137e6/CONTRIBUTING.md.

I think the previous guide was (a) in the wrong repo, (b) it contained too much information for someone just trying to implement a change and (c) missed a few things that would be good to explain to newcomers.

IMO, We should write a separate document on how to update OpenDevStack - which is a more advanced topic and the only time someone outside the core team needs remotes pointing to the `github.com/opendevstack` repos.

2018-11-26 11:51 UTC, michaelsauter commented
@cschweikert So far, BitBucket is the only support git hosting solution. We use BitBucket specific things in a couple of places, for example during provisioning, when triggering builds, and when communicating build status.

2018-11-28 20:00 UTC, rattermeyer requested changes
Except for the small typo, I really like the guide. We should add a clarifying figure later.

2018-11-29 07:47 UTC, michaelsauter commented on doc/development-guide.md
> +section), or, if they are specific to your organisation, live on only in your
I think it was actually correct :) But it's a bit complicated, so I simplified it in dc5264f.

2018-11-29 19:48 UTC, rattermeyer commented on doc/development-guide.md
> +section), or, if they are specific to your organisation, live on only in your
I think, you are right.

2018-11-29 19:48 UTC, rattermeyer approved these changes

2018-11-29 19:48 UTC, merged